### ISSUE TITLE
Write script to watch over Status repos for any private keys commited by mistake

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-github-bot#23]
### User Story

As a developer, I want to be warned if I happen to commit by mistake a private key of an ETH account which contains funds (ETH or ERC20), so that the risk of losing funds is reduced.

### Description

The script should watch all the pushes on https://github.com/status-im repos for strings that match the format of either a private key, or a 12 word recovery key. For all the keys that are found, it should look for the balance of the account, and if non-zero, send a warning over Slack to #devops channel.

Documentation for the bot is available in the [wiki](https://wiki.status.im/GitHub_bot).

<blockquote><img src="https://avatars0.githubusercontent.com/u/11767950?s=280&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im">Status</a></strong></div><div>A Mobile Ethereum Client.</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1408b0b24db472cf4f4b79d5158d6ba812049314a8a726d4f2d8780d7b760592](https://etherscan.io/tx/0x1408b0b24db472cf4f4b79d5158d6ba812049314a8a726d4f2d8780d7b760592)

**Comment by trowacat** [comment]
This is a great precaution! I will try my hand at this.

**Comment by StevenJNPearce** [comment]
Wouldn't it make more sense to use [husky](https://www.npmjs.com/package/husky) or something similar to prevent private keys from being committed in the first place? Once a private key has touched the public repo, I feel the damage has already been done.

**Comment by trowacat** [comment]
Yes, you're right, that makes more sense. The developer would be warned right away rather than having to be active on the #devops channel to realize the mistake.  A hook would warn them where they could not miss it. I'm interested if anyone has a reason for not going this route.

**Comment by PombeirP** [comment]
@trowacat I think the most important is to have a good script for checking changes before pushing. How we actually implement that on each repo will end up being an implementation detail. For instance, in this repo it would be fine to use husky, but on https://github.com/status-im/status-react/blob/develop/project.clj#L19, for instance we can invoke a script from the ClojureScript project file where we already have support for git hooks.

**Comment by trowacat** [comment]
@PombeirP Ok. Where should I submit a PR in this case?

**Comment by PombeirP** [comment]
@trowacat in this repo is fine.

**Comment by pablanopete** [comment]
Awesome stuff! 👍@trowacat

**Comment by PombeirP** [comment]
Hey @trowacat, great job! Do you think you could add the integration with `husky` too for this repo since you're at it?

**Comment by PombeirP** [comment]
@trowacat yeah, I have to admit it didn't occur to me that we'd need to extract the address before an etherscan.io query. This post seems to describe a way to achieve it, but relies on the ethers.js NPM package: https://github.com/ethers-io/ethers.js/issues/31. There is also this one which is maybe lighter weight using ethereumjs-util: https://ethereum.stackexchange.com/a/15836/30590

**Comment by PombeirP** [comment]
You know what? I wouldn't worry about the case of seed phrases. To be
honest, it is much more likely for a private key to be a problem than a
seed key.

Regarding the warning, I meant the latter, if a possible key is found but
it is unable to check for funds due to npm being missing.

**Comment by trowacat** [comment]
@PombeirP the library worked like a charm! I rewrote the script in node, I'll update my PR tonight.

**Comment by trowacat** [comment]
@PombeirP New script is pushed, let me know what you think. Thank you for the help!

**Comment by AlessandroSpallina** [comment]
is this issue closed or not?
