### ISSUE TITLE
Implement script to automate management of PR checklists

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-github-bot#27]
### User Story

As a developer, I want to be sure that I follow the guidelines for contributions. An easy way to achieve that is for the bot to automatically post a checklist to any new PRs, and only allow merging the PR when the checkboxes in the checklist are all checked.

### Description

Whenever a PR is created, [Probot](https://probot.github.io/) could look at the target repo and try to retrieve for a checklist definition (could be located in the `.github/github-bot.yml` config file). If one is found, it would post a comment to the PR with the checklist.
It would then need to monitor PR comment changes to update the PR state according to the state of the checklist (similar to what the [WIP plugin](https://github.com/wip/app) is already doing).

Documentation for the bot is available in the [wiki](https://wiki.status.im/GitHub_bot), and several existing scripts already exist in the repo that can serve as reference/inspiration.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd518e246ef274b654143a01dda9bed89876b7c972ea622775555434dc1e4791f](https://etherscan.io/tx/0xd518e246ef274b654143a01dda9bed89876b7c972ea622775555434dc1e4791f)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe90e97d5c352b3719e3522f2b166ecf68097a432b861d0fa3dc4092467a9fdc4](https://etherscan.io/tx/0xe90e97d5c352b3719e3522f2b166ecf68097a432b861d0fa3dc4092467a9fdc4)

**Comment by virneo** [comment]
I am working on bot PRChecklist.

**Comment by realphi** [comment]
How bot should verify conditions are met for check list items to mark them as complete?
Will a comment like 'item done' suffice or something else?

**Comment by virneo** [comment]
The app is ready now, now deploying so that it can be installed.

**Comment by virneo** [comment]
Hello guys, I created the app and hosted it on heroku. Do you guys want this feature in status-github-bot? Here is the current repo
https://github.com/virneo/prchecklist

**Comment by PombeirP** [comment]
Hi @virneo, that's great news! I'm currently on vacation, but will take a look at it as soon as I get back in a couple of weeks. Thanks for working on this!

**Comment by virneo** [comment]
https://github.com/status-im/status-github-bot/pull/28
I have a question regarding the probot version in this app. Where shall I redirect my question?

**Comment by PombeirP** [comment]
I'm the only one currently working on this repo. I can try to answer your questions, I just can't guarantee a quick answer.

**Comment by virneo** [comment]
I updated the probot version to 6.2 in order to get support for github checksuite api. The app showed no problems with this update except a warning regarding response.meta renamed to response.header

**Comment by virneo** [comment]
Nevermind, reverted the version back to probot 5.0 since I am not using checks api anymore.

**Comment by pablanopete** [comment]
This bounty has been confirmed, sorry for the long hold out!

**Comment by virneo** [comment]
Thanks, happy to take another issue.
