### ISSUE TITLE
Have bot ping relevant developers regarding issues pending bounty approval 

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-github-bot#5]
### User Story

As a developer, I want to know when a new issue from my team is pending bounty approval, so that I can react more quickly without having to search for information.

### Description

A better way to address this issue would be to leverage the new GitHub bot (written on the [Probot framework](https://probot.github.io/)) to [listen to issue label changes](https://developer.github.com/v3/issues/events/), specifically when an issue is labeled with `bounty-awaiting-approval`, and then act on it by notifying the [team members from the respective repository](https://developer.github.com/v3/repos/collaborators/#list-collaborators) on [Slack](https://github.com/status-im/status-github-bot/blob/master/scripts/greet-new-contributor.js#L73) (either through a DM or a mention on a given room).

Since GitHub user names don't necessarily match Slack user names, the bot would need to read the mapping from a file (JSON or YAML). The same list from #4 should be reused. Only the implementation is required, the file itself will be filled later on by the team.

Documentation for the bot is available in the [wiki](https://wiki.status.im/GitHub_bot).

**Comment by ImFeelingDucky** [comment]
Hey there :smiley: Can I take this on?

PS: What you're doing at Status is awesome!!

**Comment by PombeirP** [comment]
Hey @ImFeelingDucky, that would be great! Let me know if you need any guidance.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x758f7966c96f7ee197d11268b503b8ecdf1274d9b8103b3e3a4c8105902d023e](https://etherscan.io/tx/0x758f7966c96f7ee197d11268b503b8ecdf1274d9b8103b3e3a4c8105902d023e)
