### ISSUE TITLE
Have bot ping Status Open Bounty funders when three thumbs up are added to a bounty issue

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-github-bot#6]
### User Story

As a SOB funder, I want to know when a new issue has been approved by developers, so that I can react more quickly without having to search for information.

### Description

A better way to address this issue would be to leverage the new GitHub bot (written on the [Probot framework](https://probot.github.io/)) to:

1. [listen to issue comment changes](https://developer.github.com/v3/activity/events/types/#issuecommentevent);
1. check if issue is labelled with `bounty-awaiting-approval`;
1. check the [reactions summary in the issue](https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue) and proceed only if the number of `+1` reactions is > 2;
1. act on it by notifying the Status Open Bounty funders [on Slack through a DM](https://github.com/status-im/status-github-bot/blob/master/scripts/greet-new-contributor.js#L73). Location for list of funders TBD in yml config file. List will be filled later on by team.

Documentation for the bot is available in the [wiki](https://wiki.status.im/GitHub_bot).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd6f22ee9fa35270207cd3b6f467c9eb03df80aaf4c333b54a5b894280d14f57c](https://etherscan.io/tx/0xd6f22ee9fa35270207cd3b6f467c9eb03df80aaf4c333b54a5b894280d14f57c)

**Comment by seifane** [comment]
Hey, 
I wanted to start working on the issue but `npm test` gives me linting errors. :/
I attached the log below. Also I wanted to ask if there's anyway to quickly test the project ?
Regards :)

[log.txt](https://github.com/status-im/status-github-bot/files/1670728/log.txt)

**Comment by PombeirP** [comment]
Hi @seifane! Thanks for the heads up, I'd forgotten to run a linter in the rush to get a first version running. I've now fixed that.

In order to quickly test the project, I'd recommend following the Probot documentation (creating a test GitHub app on your account and configuring the project `.env` file with the values generated).

**Comment by realphi** [comment]
Is this issue still unfixed? or it is awarded as the openbounty bot says above. #

**Comment by PombeirP** [comment]
Hi @realphi. This issue is still unfixed, not sure what happened with the open bounty there. Ping @pablanopete
