### ISSUE TITLE
Have bot move SOB issue to 'PR submitted' column if a PR references a SOB issue

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-github-bot#9]
### User Story

As a Status Open Bounty maintainer, I don't want to have to manually manage checking when a pull request is submitted against a SOB issue that is currently in the `Bounty Open` or `Stale Bounties`  columns and moving the project card that represents the issue to the `PR Submitted` column.

### Description

A better way to address this issue would be to leverage the new GitHub bot (written on the [Probot framework](https://probot.github.io/)) to:
- [listen to issue `referenced` events](https://developer.github.com/v3/issues/events/);
- check if the issue that is referenced is assigned the `bounty` label;
- [check if there is a project card in the `Status SOB Swarm`](https://github.com/status-im/status-github-bot/blob/master/scripts/assign-to-bounty-awaiting-for-approval.js#L133) organizational project board in the `Bounty Open` or `Stale Bounties`.

and if the conditions are met, act on it by:
- [moving the project card](https://github.com/status-im/status-github-bot/blob/master/scripts/assign-approved-pr-to-test.js#L223) that represents the bounty issue to the `PR Submitted` column.
- [sending a notification to Slack](https://github.com/status-im/status-github-bot/blob/master/scripts/greet-new-contributor.js#L73), saying something like:
  > A new PR was submitted for a SOB issue\n${pr.html_url}

Documentation for the bot is available in the [wiki](https://wiki.status.im/GitHub_bot).

### Acceptance criteria

- The project board, column and label names are fetched from the `.github/ github-bot.yml` config file;
- The script follows the style of existing scripts and the prescriptions made in the documentation;
- There is a new environment variable (e.g. `DRY_RUN_SOB_PR_SUBMITTED`) that allows [toggling a dry-run](https://github.com/status-im/status-github-bot/blob/master/scripts/assign-approved-pr-to-test.js#L250) for this particular script for easier testing.
- The bot has been tested locally to ensure it works as expected.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9199af758dbc76b5eb584f19c280291abe40bbda50d2df289bfdc25f835ea9f7](https://etherscan.io/tx/0x9199af758dbc76b5eb584f19c280291abe40bbda50d2df289bfdc25f835ea9f7)

**Comment by ImFeelingDucky** [comment]
I'm happy to take this on. Will use what I've learnt from #8 for a better PR.

Would just like a little context:
"check if there is a project card in the Status SOB Swarm organizational project board in the Bounty Open or Stale Bounties." Is there a link to this board? And is this for one specific repo only?

Thanks!

**Comment by andytudhope** [comment]
Hi @ImFeelingDucky! The board is [here](https://github.com/orgs/status-im/projects/3), but may only be viewable by org members... 
1. We have 2 columns - `Bounty Open` and `Stale Bounties` and only populate them with issues that have the label `bounty` assigned to them. If someone submits a PR with the syntax `Fixes #N`, it shows up as a reference in that issue and you should be able to use that to move the card from either of those two columns to the next one on the board, `PR Submitted`.
2. The board is for the whole organisation, not just one repo, as it is where we manage all Status bounties from.

**Comment by PombeirP** [comment]
@ImFeelingDucky I'd recommend creating your own test GitHub organization, and a org project board (not repo-level) that mimics this structure:

![image](https://user-images.githubusercontent.com/138074/35649847-95049718-06da-11e8-9876-f2dce5687d68.png)

That will make it simple for you to test the script in real-world conditions.

**Comment by ImFeelingDucky** [comment]
Thanks, @andytudhope and @PombeirP, that was very helpful!
